- name: Install common packages
  ansible.builtin.package:
    name: 
      - python3
      - ceph-common
  
- name: Execute MGR specific tasks
  ansible.builtin.include_tasks: mgr.yml
  when: '"mgr" in group_names'

- name: Execute MON specific tasks
  ansible.builtin.include_tasks: mon.yml
  when: '"mon" in group_names'

- name: Execute OSD specific tasks
  ansible.builtin.include_tasks: osd.yml
  when: '"osd" in group_names'
