docker_version: latest

docker_proxies: {}

docker_insecure_registries: []

docker_tls:
  enable: false
  verify: false

docker_logs:
  driver: json-file
  opts: {}

docker_data_root: /var/lib/docker/
