dependencies:
  - role: tesselate.linux.docker
    tags: docker
  - role: tesselate.linux.chrony_orchestrator
    vars:
      chrony_orchestrator_client_groups:
        - mon
        - osd
      chrony_orchestrator_server_groups:
        - mgr
    tags: chrony
